---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kured-cronjob-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kured-daemonset-editor
subjects:
- kind: ServiceAccount
  name: kured-cronjob-sa
  namespace: kube-system
