---
- name: register the context
  command: "az aks get-credentials --resource-group {{ aks_resource_group }} --name {{ aks_resource_name }}"
  register: azure_credentials_output
- debug:
    var: azure_credentials_output
