---
- hosts: all
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: False

  tasks:

    - include_role:
        name: azure-login
      vars:
        user: "{{ ansible_client_id }}"
        password: "{{ ansible_client_secret }}"
        tenant: "{{ tenant_id }}"


    - include_role: 
        name: custom-cluster
      vars:
        aks_dict: "{{ application_aks_cluster }}"
      when: true