---
- hosts: all
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: False

  tasks:

    - include_role: 
        name: custom-cluster
      vars:
        aks_dict: "{{ application_aks_cluster }}"
      when: true